### ISSUE TITLE
Rename repository, update documentation & assets

### ISSUE THREAD

**Issue by celanthe** [camunda-community-hub/camunda-platform-7-camel#108]
Hi Jan,

This issue is being opened to ask if you would be open to renaming your extension on GitHub via the 'Settings' option to reference Camunda Platform 7 rather than Camunda BPM. (For example: camunda-platform-7-camel) This change will also likely impact any screenshots you have in the README that reference Camunda BPM, and this verbiage will need to also be updated throughout the repo's documentation as a whole if you choose to make these changes. You can also make use of [Shields.io badges](https://github.com/camunda-community-hub/community/blob/main/extension-lifecycle.md) to indicate which version of Camunda your extension is compatible with. 

While it is not a **requirement** that you rename your extension to align with Camunda Platform 7, we would **greatly** appreciate it if you could make these changes, and merge them anytime after April 12th, 2022.

 if you have any questions or require any assistance, please do not hesitate to reach out to @camunda-community-hub/devrel! :)

**Comment by akeller** [comment]
@jangalinski @berndruecker are you interested in making these changes? If renaming the entire project is too difficult, I would recommend at least changing the name of Camunda BPM to Camunda Platform 7 in the README.

**Comment by jangalinski** [comment]
It might be a bit far fetched, but a great solution would be a generic camunda camel model that can work with either platform 7 or 8 ... so kind of a meta-model ...

options:

a) rename this one and create a new "works with both" camel extension
b) leave this one for now and just flag the readme as "currently platform 7 only"

opinions?

**Comment by berndruecker** [comment]
I renamed and add a label for C7 for the moment to make this clear (because everything else will take time anyway).

I did not touch groupId / artifactID so far (@jangalinski: Feel free to take this on if you like :-))

Thinking about it, I think we should go for a new project targeting Camunda 8 - as it will look quite a bit different (especially as it needs to take an endpoint to connect to compared to [talk to the engine in-vm](https://github.com/camunda-community-hub/camunda-platform-7-camel/blob/master/camunda-bpm-camel-common/src/main/java/org/camunda/bpm/camel/component/CamundaBpmEndpointDefaultImpl.java).

In general, there we would need a new Camel endpoints, e.g. 
`camunda-8[somehow the endpoint mus go here]://start` in contrast to
`camunda-bpm://start` (which goes to C7 and I vote for not touching it, even if the naming is not optimal)

And a task worker that subscribes to the task type `camel` (needs some additional thought).

**Comment by jangalinski** [comment]
"if I like" - no sorry, not at the moment, busy with other topics. Let's leave it for now.

**Comment by jangalinski** [comment]
If you can remember ... I did the "zeebe-camel-facebam" in Berlin using a zeebe-camel early adopter example ... so at least I have some fragments.

I would prefer having C7 and C8 camel under the same repo as the concepts (correlation, external task, ...) are very similar ...

**Comment by berndruecker** [comment]
Let's pick the Camel & C8 topic up again when we see demand for it.
Of course i remember https://github.com/holunda-io/camel-zeebe and https://github.com/holunda-io/zeebe-camel-facebam
